# %% Configure the problem

# Standard imports
import matplotlib
import numpy as np
import pyvista as pv
import openmdao.api as om
from time import time_ns

matplotlib.use('Agg')

OBJECTIVE_NAME = 'pressure.pressure_drop'
DENSITY_CONSTRAINT_NAME = 'proj.density_constraint.max_density'
DENSITY_CONSTRAINT_UPPER = 1.1
DRIVER_CASES_FILENAME = 'driver_cases.sql'
TRAJECTORY_PLOT_FILENAME = 'optimization_trajectory.png'

PIPE_RADIUS = 0.25
PIPE_FLOW_RATE = 0.1
PRESSURE_DROP_REF = 1.0e4


# SPI2py API imports
from SPI2py.API.system import System, Components, Interconnects, LinearSplineComponent, Interconnect
from SPI2py.API.projection import Projections, ProjectionConstraint
from SPI2py.API.objectives import BoundingBoxVolume, PressureDrop
from SPI2py.API.utilities import Multiplexer


# SPI2py supporting model imports
from SPI2py.models.physics.distributed.mesh import generate_mesh
from SPI2py.models.utilities.visualization import plot_grid, plot_AABB, plot_driver_trajectory


# Start a timer for tracking the workflow
t0 = time_ns()


# Configure JAX settings
# jax.config.update("jax_enable_x64", True)
# jax.config.update("jax_debug_nans", True)


# Define the domain as a uniform grid
x_min, x_max = (0, 14)
y_min, y_max = (0, 7)
z_min, z_max = (0, 7)
element_size = 0.3
nodes, elements, centers, nx, ny, nz, lx, ly, lz = generate_mesh(
    x_min, x_max, y_min, y_max, z_min, z_max, element_size=element_size)
centers = centers.reshape(nx, ny, nz, 1, 3)


# %% Initialize the problem and model structure


# OpenMDAO problem and model
prob = om.Problem()
model = prob.model

# Recorder that writes to a sqlite file
rec = om.SqliteRecorder('cases.sql')
prob.add_recorder(rec)
prob.recording_options['record_inputs'] = True
prob.recording_options['record_outputs'] = True

# SPI2py Nested Groups
system = System()
comps = Components()
ints = Interconnects()
proj = Projections()

model.add_subsystem('system', system)
model.system.add_subsystem('comps', comps)
model.system.add_subsystem('ints', ints)


# %% Define the system


# Define one fixed red obstacle. It is a long cylinder spanning from y=0
# toward the top of the domain, centered near the bottom in z.
x_mid = 0.5 * (x_min + x_max)
y_mid = 0.5 * (y_min + y_max)
obstacle_radius = 0.60
obstacle_z = obstacle_radius
obstacle_start = [x_mid, y_min + obstacle_radius, obstacle_z]
obstacle_end = [x_mid, y_max - 0.80, obstacle_z]

obstacle = LinearSplineComponent(
    start_points=[obstacle_start],
    end_points=[obstacle_end],
    radii=[obstacle_radius],
    port_positions=[obstacle_start, obstacle_end],
    color='red',
)
model.system.comps.add_subsystem('obstacle', obstacle)


# Define one routed pipe from the x-min YZ plane to the x-max YZ plane.
# A straight low-z pipe would intersect the red obstacle, so the initial route
# climbs over it. With n_segments=6, there are 3 segments on either side of
# the middle control point.
pipe = Interconnect(radius=PIPE_RADIUS, n_segments=6, color='gray')
model.system.ints.add_subsystem('pipe', pipe)

pipe_start = np.array([[x_min, y_mid, PIPE_RADIUS]])
pipe_end = np.array([[x_max, y_mid, PIPE_RADIUS]])
pipe_control_points = np.array([
    [2.25, y_mid, PIPE_RADIUS],
    [4.60, y_mid, 2.00],
    [x_mid, y_mid + 0.25, 2.10],
    [9.40, y_mid, 2.00],
    [11.75, y_mid, PIPE_RADIUS],
])


# Now combine the obstacle and pipe geometry for plotting, bounding boxes, and
# projection. The obstacle is represented as a two-point capsule; the pipe is a
# seven-point polyline generated by the Interconnect component.
obstacle_capsule_points = Multiplexer(n_i=[1, 1], m=3)
obstacle_capsule_radii = Multiplexer(n_i=[1, 1], m=1)
mux_centers = Multiplexer(n_i=[2, 7], m=3)
mux_radii = Multiplexer(n_i=[2, 7], m=1)

prob.model.add_subsystem('obstacle_capsule_points', obstacle_capsule_points)
prob.model.add_subsystem('obstacle_capsule_radii', obstacle_capsule_radii)
prob.model.add_subsystem('mux_centers', mux_centers)
prob.model.add_subsystem('mux_radii', mux_radii)

prob.model.connect('system.comps.obstacle.updated_start_points', 'obstacle_capsule_points.input_0')
prob.model.connect('system.comps.obstacle.updated_end_points', 'obstacle_capsule_points.input_1')
prob.model.connect('system.comps.obstacle.updated_radii', 'obstacle_capsule_radii.input_0')
prob.model.connect('system.comps.obstacle.updated_radii', 'obstacle_capsule_radii.input_1')

prob.model.connect('obstacle_capsule_points.stacked_output', 'mux_centers.input_0')
prob.model.connect('system.ints.pipe.updated_cyl_positions', 'mux_centers.input_1')
prob.model.connect('obstacle_capsule_radii.stacked_output', 'mux_radii.input_0')
prob.model.connect('system.ints.pipe.updated_cyl_radius', 'mux_radii.input_1')


# Aggregate pseudo-densities for collision checking.
model.add_subsystem('proj', proj)

projection_constraint = ProjectionConstraint(
    n_components=0,
    n_interconnects=2,
    rho_min=1e-2,
    mesh_size=element_size,
    mesh_centers=centers,
)
model.proj.add_subsystem('density_constraint', projection_constraint)

model.connect('obstacle_capsule_points.stacked_output', 'proj.density_constraint.interconnect_points_0')
model.connect('obstacle_capsule_radii.stacked_output', 'proj.density_constraint.interconnect_radius_0')
model.connect('system.ints.pipe.updated_cyl_positions', 'proj.density_constraint.interconnect_points_1')
model.connect('system.ints.pipe.updated_cyl_radius', 'proj.density_constraint.interconnect_radius_1')


# %% Configure the optimization


# Use per-control-point bounds to keep the pipe ordered from x_min to x_max
# while allowing y/z motion around or over the red obstacle.
pipe_control_lower = np.array([
    [1.00, y_min + PIPE_RADIUS, z_min + PIPE_RADIUS],
    [3.50, y_min + PIPE_RADIUS, z_min + PIPE_RADIUS],
    [6.50, y_min + PIPE_RADIUS, z_min + PIPE_RADIUS],
    [8.50, y_min + PIPE_RADIUS, z_min + PIPE_RADIUS],
    [11.00, y_min + PIPE_RADIUS, z_min + PIPE_RADIUS],
])
pipe_control_upper = np.array([
    [3.00, y_max - PIPE_RADIUS, z_max - PIPE_RADIUS],
    [5.50, y_max - PIPE_RADIUS, z_max - PIPE_RADIUS],
    [7.50, y_max - PIPE_RADIUS, z_max - PIPE_RADIUS],
    [10.50, y_max - PIPE_RADIUS, z_max - PIPE_RADIUS],
    [13.00, y_max - PIPE_RADIUS, z_max - PIPE_RADIUS],
])
prob.model.add_design_var(
    'system.ints.pipe.control_points',
    ref=1.0,
    lower=pipe_control_lower,
    upper=pipe_control_upper,
)


# Keep the bounding box component for plotting the current geometry envelope.
bbv = BoundingBoxVolume()
model.add_subsystem('bbv', bbv)
prob.model.connect('mux_centers.stacked_output', 'bbv.centers')
prob.model.connect('mux_radii.stacked_output', 'bbv.radii')


# Pressure drop is the optimization objective.
pressure = PressureDrop()
model.add_subsystem('pressure', pressure)
prob.model.connect('system.ints.pipe.updated_cyl_positions', 'pressure.coordinates')
prob.model.connect('system.ints.pipe.updated_cyl_radius', 'pressure.pipe_radius')
prob.model.add_objective(OBJECTIVE_NAME, ref=PRESSURE_DROP_REF)


# Set the constraint(s)
prob.model.add_constraint(DENSITY_CONSTRAINT_NAME, upper=DENSITY_CONSTRAINT_UPPER)


# Set up the optimizer
prob.driver = om.ScipyOptimizeDriver()
prob.driver.options['maxiter'] = 50

# Driver-level recorder for objective/constraint trajectories.
driver_rec = om.SqliteRecorder(DRIVER_CASES_FILENAME)
prob.driver.add_recorder(driver_rec)
prob.driver.recording_options['record_desvars'] = True
prob.driver.recording_options['record_objectives'] = True
prob.driver.recording_options['record_constraints'] = True
prob.driver.recording_options['record_inputs'] = False
prob.driver.recording_options['record_outputs'] = True
prob.driver.recording_options['record_residuals'] = False
prob.driver.recording_options['includes'] = [OBJECTIVE_NAME, DENSITY_CONSTRAINT_NAME]


# ...
prob.setup()


# %% Run the model once to check the initial state and sensitivities


# Set the fixed endpoints and initial route.
prob.set_val('system.ints.pipe.start_point', pipe_start)
prob.set_val('system.ints.pipe.end_point', pipe_end)
prob.set_val('system.ints.pipe.control_points', pipe_control_points)
prob.set_val('pressure.flow_rate', PIPE_FLOW_RATE)


# Run the model once
t1 = time_ns()
prob.run_model()
t2 = time_ns()

print(f"Run time: {(t2 - t1) / 1e9} seconds")


# Check the initial state
print("Pressure Drop Before:", prob.get_val(OBJECTIVE_NAME))
print("BBV Before:", prob.get_val('bbv.volume'))
print("Max Density:", prob.get_val(DENSITY_CONSTRAINT_NAME))


# %% Now run the optimization

prob.record('before')


# Run the optimization
t3 = time_ns()
prob.run_driver()
t4 = time_ns()
print(f"Optimization time: {(t4 - t3) / 1e9} seconds")

outputs_dir = prob.get_outputs_dir()
reports_dir = prob.get_reports_dir()
prob.record('after')
prob.cleanup()

trajectory_plot = plot_driver_trajectory(
    outputs_dir,
    reports_dir,
    objective_name=OBJECTIVE_NAME,
    constraint_name=DENSITY_CONSTRAINT_NAME,
    constraint_upper=DENSITY_CONSTRAINT_UPPER,
    driver_cases_filename=DRIVER_CASES_FILENAME,
    trajectory_plot_filename=TRAJECTORY_PLOT_FILENAME,
)
if trajectory_plot is not None:
    print(f"Optimization trajectory plot: {trajectory_plot}")


# Check the final state
print("Pressure Drop After:", prob.get_val(OBJECTIVE_NAME))
print("BBV After:", prob.get_val('bbv.volume'))
print("Max Density:", prob.get_val(DENSITY_CONSTRAINT_NAME))

bounds_after = prob.get_val('bbv.bounds')
densities_after = prob.get_val('proj.density_constraint.aggregated_densities')


# %% Plot the results


t5 = time_ns()

# Create multiple subplots
plotter = pv.Plotter(shape=(2, 2), window_size=(1500, 500), lighting='light kit')

# Define the subplots
sp1, sp2, sp3, sp4 = (0, 0), (1, 0), (0, 1), (1, 1)

# Load the case recorded
cr = om.CaseReader(prob.get_outputs_dir() / 'cases.sql')
before = cr.get_case('before')
after = cr.get_case('after')


# %% Plot the System Before Optimization


# Load the recorded case before optimization
prob.load_case(before)

plotter.subplot(*sp1)
plotter.add_title("Before")

plot_grid(plotter, sp1, centers, element_size, densities=None, min_opacity=0.0)
model.system.draw(plotter, sp1, prob)
plot_AABB(plotter, sp1, prob.get_val('bbv.bounds'), color='gray', opacity=0)

model.proj.density_constraint.draw(plotter, sp2, prob)


# %% Plot the System After Optimization


# Load the recorded case after optimization
prob.load_case(after)

plotter.subplot(*sp3)
plotter.add_title("After")

plot_grid(plotter, sp3, centers, element_size, densities=None, min_opacity=0.0)
model.system.draw(plotter, sp3, prob)
plot_AABB(plotter, sp3, prob.get_val('bbv.bounds'), color='gray', opacity=0)

model.proj.density_constraint.draw(plotter, sp4, prob)


# %% Plotter configurations


plotter.link_views()
plotter.show_axes()
# plotter.enable_shadows()
# plotter.enable_ssao(radius=0.5)
plotter.enable_anti_aliasing('fxaa')
plotter.view_xy()
plotter.show()


t6 = time_ns()
print(f"Plot time: {(t6 - t5) / 1e9} seconds")
print(f"Total time: {(t6 - t0) / 1e9} seconds")
print('Done')


# %% Additional code for debugging


# prob.check_totals(compact_print=True)
# prob.check_partials(compact_print=True, show_only_incorrect=True)

# Select whether to use exact or finite difference totals for the optimization
# prob.model.approx_totals(method='exact')
# or
# prob.model.approx_totals(method='fd')

# Check the total derivative of an output wrt a design variable
# totals_c_approx = prob.compute_totals(of=[DENSITY_CONSTRAINT_NAME],
#                                       wrt=['system.ints.pipe.control_points'])
